import { type HumanizeUnitOptions, humanizeUnit } from './humanizeUnit.js';
import { Binary, SI, Time, type UnitArray } from './units.js';

/**
 * Signature shared by all helper functions generated by this module.
 */
export type HumanizeHelper = (
  value: number | null | undefined,
  options?: Omit<HumanizeUnitOptions, 'units' | 'postfix'>,
) => string;

/**
 * Factory that binds a unit table and postfix to `humanizeUnit`.
 *
 * @param units Unit definitions applied by the generated helper.
 * @param postfix Postfix appended after the unit notation.
 * @returns Specialized helper function.
 */
const createHelper =
  (units: UnitArray, postfix: string = ''): HumanizeHelper =>
  (value, options) =>
    humanizeUnit(value, { ...options, units, postfix });

/** Formats counts using SI prefixes (k, M, G…). */
export const humanizeCount = createHelper(SI);
/** Formats decimal bytes (kB, MB, GB…). */
export const humanizeBytes = createHelper(SI, 'B');
/** Alias of {@link humanizeBytes}. */
export const humanizeBytesDecimal = createHelper(SI, 'B');
/** Formats binary bytes (KiB, MiB, GiB…). */
export const humanizeBytesBinary = createHelper(Binary, 'B');
/** Formats decimal storage capacities. */
export const humanizeStorage = createHelper(SI, 'B');
/** Formats binary storage capacities. */
export const humanizeStorageBinary = createHelper(Binary, 'B');
/** Formats durations from milliseconds to years. */
export const humanizeTime = createHelper(Time);
/** Formats distances using SI meters. */
export const humanizeDistance = createHelper(SI, 'm');
/** Formats masses using SI grams. */
export const humanizeMass = createHelper(SI, 'g');
/** Formats accelerations using meters per second squared. */
export const humanizeAcceleration = createHelper(SI, 'm/s^2');
/** Formats electric charge (coulomb). */
export const humanizeCharge = createHelper(SI, 'C');
/** Formats momentum (newton second). */
export const humanizeMomentum = createHelper(SI, 'N*s');
/** Formats power (watt). */
export const humanizePower = createHelper(SI, 'W');
/** Formats velocity (meter per second). */
export const humanizeVelocity = createHelper(SI, 'm/s');
/** Formats volume (cubic meter). */
export const humanizeVolume = createHelper(SI, 'm^3');
/** Formats liquid volume (liter). */
export const humanizeLiquidVolume = createHelper(SI, 'L');
/** Formats temperature in Celsius. */
export const humanizeTemperature = createHelper(SI, '°C');
/** Formats temperature in Kelvin. */
export const humanizeTemperatureKelvin = createHelper(SI, '°K');
/** Formats pressure (pascal). */
export const humanizePressure = createHelper(SI, 'Pa');
/** Formats force (newton). */
export const humanizeForce = createHelper(SI, 'N');
/** Formats torque (newton meter). */
export const humanizeTorque = createHelper(SI, 'N*m');
/** Formats energy (joule). */
export const humanizeEnergy = createHelper(SI, 'J');
/** Formats voltage (volt). */
export const humanizeVoltage = createHelper(SI, 'V');
/** Formats current (ampere). */
export const humanizeCurrent = createHelper(SI, 'A');
/** Formats resistance (ohm). */
export const humanizeResistance = createHelper(SI, 'Ω');
/** Formats capacitance (farad). */
export const humanizeCapacitance = createHelper(SI, 'F');
/** Formats inductance (henry). */
export const humanizeInductance = createHelper(SI, 'H');
/** Formats frequency (hertz). */
export const humanizeFrequency = createHelper(SI, 'Hz');
/** Formats angle (degree). */
export const humanizeAngle = createHelper(SI, '°');
/** Formats length (meter). */
export const humanizeLength = createHelper(SI, 'm');
/** Formats area (square meter). */
export const humanizeArea = createHelper(SI, 'm^2');
/** Formats volumetric flow rates (cubic meter per second). */
export const humanizeVolumeFlowRate = createHelper(SI, 'm^3/s');
/** Formats mass flow rates (kilogram per second). */
export const humanizeMassFlowRate = createHelper(SI, 'kg/s');
/** Formats density (kilogram per cubic meter). */
export const humanizeDensity = createHelper(SI, 'kg/m^3');
/** Formats concentration (mole per cubic meter). */
export const humanizeConcentration = createHelper(SI, 'mol/m^3');
/** Formats molar mass (gram per mole). */
export const humanizeMolarMass = createHelper(SI, 'g/mol');
/** Formats molar volume (cubic meter per mole). */
export const humanizeMolarVolume = createHelper(SI, 'm^3/mol');
/** Formats molar density (mole per cubic meter). */
export const humanizeMolarDensity = createHelper(SI, 'mol/m^3');
/** Formats molar concentration (alias of {@link humanizeConcentration}). */
export const humanizeMolarConcentration = createHelper(SI, 'mol/m^3');
/** Formats magnetic flux (weber). */
export const humanizeMagneticFlux = createHelper(SI, 'Wb');
/** Formats magnetic flux density (tesla). */
export const humanizeMagneticFluxDensity = createHelper(SI, 'T');
/** Formats illuminance (lux). */
export const humanizeIlluminance = createHelper(SI, 'lx');
/** Formats luminous flux (lumen). */
export const humanizeLuminousFlux = createHelper(SI, 'lm');
/** Formats radioactivity (becquerel). */
export const humanizeRadioactivity = createHelper(SI, 'Bq');
/** Formats equivalent dose (sievert). */
export const humanizeRadiationDoseEquivalent = createHelper(SI, 'Sv');
/** Formats absorbed dose (gray). */
export const humanizeRadiationDoseAbsorbed = createHelper(SI, 'Gy');
/** Formats catalytic activity (katal). */
export const humanizeCatalyticActivity = createHelper(SI, 'kat');
