import { type HumanizeUnitOptions, humanizeUnit } from './humanizeUnit.js';
import { Binary, SI, Time, type UnitArray } from './units.js';

/**
 * Configuration passed to helper shortcuts. Equivalent to
 * {@link HumanizeUnitOptions} without the `units` table.
 */
export type HumanizeHelperOptions = Omit<HumanizeUnitOptions, 'units' | 'postfix'>;

/**
 * Signature shared by all helper functions generated by this module.
 */
export type HumanizeHelper = (value: number | null | undefined, options?: HumanizeHelperOptions) => string;

/**
 * Factory that binds a unit table to `humanizeUnit`.
 *
 * @param units Unit definitions applied by the generated helper.
 * @returns Specialized helper function.
 */
const createHumanizeHelper =
  (units: UnitArray): HumanizeHelper =>
  (value, options) =>
    humanizeUnit(value, { ...options, units });

/**
 * Factory that binds a unit table and postfix to `humanizeUnit`.
 *
 * @param units Unit definitions applied by the generated helper.
 * @param postfix Postfix appended after the unit notation.
 * @returns Specialized helper function.
 */
const createHumanizeHelperWithPostfix =
  (units: UnitArray, postfix: string): HumanizeHelper =>
  (value, options) =>
    humanizeUnit(value, { ...options, units, postfix });

/** Formats counts using SI prefixes (k, M, G…). */
export const humanizeCount = createHumanizeHelper(SI);
/** Formats decimal bytes (kB, MB, GB…). */
export const humanizeBytes = createHumanizeHelperWithPostfix(SI, 'B');
/** Alias of {@link humanizeBytes}. */
export const humanizeBytesDecimal = createHumanizeHelperWithPostfix(SI, 'B');
/** Formats binary bytes (KiB, MiB, GiB…). */
export const humanizeBytesBinary = createHumanizeHelperWithPostfix(Binary, 'B');
/** Formats decimal storage capacities. */
export const humanizeStorage = createHumanizeHelperWithPostfix(SI, 'B');
/** Formats binary storage capacities. */
export const humanizeStorageBinary = createHumanizeHelperWithPostfix(Binary, 'B');
/** Formats durations from milliseconds to years. */
export const humanizeTime = createHumanizeHelper(Time);
/** Formats distances using SI meters. */
export const humanizeDistance = createHumanizeHelperWithPostfix(SI, 'm');
/** Formats masses using SI grams. */
export const humanizeMass = createHumanizeHelperWithPostfix(SI, 'g');
/** Formats accelerations using meters per second squared. */
export const humanizeAcceleration = createHumanizeHelperWithPostfix(SI, 'm/s^2');
/** Formats electric charge (coulomb). */
export const humanizeCharge = createHumanizeHelperWithPostfix(SI, 'C');
/** Formats momentum (newton second). */
export const humanizeMomentum = createHumanizeHelperWithPostfix(SI, 'N*s');
/** Formats power (watt). */
export const humanizePower = createHumanizeHelperWithPostfix(SI, 'W');
/** Formats velocity (meter per second). */
export const humanizeVelocity = createHumanizeHelperWithPostfix(SI, 'm/s');
/** Formats volume (cubic meter). */
export const humanizeVolume = createHumanizeHelperWithPostfix(SI, 'm^3');
/** Formats liquid volume (liter). */
export const humanizeLiquidVolume = createHumanizeHelperWithPostfix(SI, 'L');
/** Formats temperature in Celsius. */
export const humanizeTemperature = createHumanizeHelperWithPostfix(SI, '°C');
/** Formats temperature in Kelvin. */
export const humanizeTemperatureKelvin = createHumanizeHelperWithPostfix(SI, '°K');
/** Formats pressure (pascal). */
export const humanizePressure = createHumanizeHelperWithPostfix(SI, 'Pa');
/** Formats force (newton). */
export const humanizeForce = createHumanizeHelperWithPostfix(SI, 'N');
/** Formats torque (newton meter). */
export const humanizeTorque = createHumanizeHelperWithPostfix(SI, 'N*m');
/** Formats energy (joule). */
export const humanizeEnergy = createHumanizeHelperWithPostfix(SI, 'J');
/** Formats voltage (volt). */
export const humanizeVoltage = createHumanizeHelperWithPostfix(SI, 'V');
/** Formats current (ampere). */
export const humanizeCurrent = createHumanizeHelperWithPostfix(SI, 'A');
/** Formats resistance (ohm). */
export const humanizeResistance = createHumanizeHelperWithPostfix(SI, 'Ω');
/** Formats capacitance (farad). */
export const humanizeCapacitance = createHumanizeHelperWithPostfix(SI, 'F');
/** Formats inductance (henry). */
export const humanizeInductance = createHumanizeHelperWithPostfix(SI, 'H');
/** Formats frequency (hertz). */
export const humanizeFrequency = createHumanizeHelperWithPostfix(SI, 'Hz');
/** Formats angle (degree). */
export const humanizeAngle = createHumanizeHelperWithPostfix(SI, '°');
/** Formats length (meter). */
export const humanizeLength = createHumanizeHelperWithPostfix(SI, 'm');
/** Formats area (square meter). */
export const humanizeArea = createHumanizeHelperWithPostfix(SI, 'm^2');
/** Formats volumetric flow rates (cubic meter per second). */
export const humanizeVolumeFlowRate = createHumanizeHelperWithPostfix(SI, 'm^3/s');
/** Formats mass flow rates (kilogram per second). */
export const humanizeMassFlowRate = createHumanizeHelperWithPostfix(SI, 'kg/s');
/** Formats density (kilogram per cubic meter). */
export const humanizeDensity = createHumanizeHelperWithPostfix(SI, 'kg/m^3');
/** Formats concentration (mole per cubic meter). */
export const humanizeConcentration = createHumanizeHelperWithPostfix(SI, 'mol/m^3');
/** Formats molar mass (gram per mole). */
export const humanizeMolarMass = createHumanizeHelperWithPostfix(SI, 'g/mol');
/** Formats molar volume (cubic meter per mole). */
export const humanizeMolarVolume = createHumanizeHelperWithPostfix(SI, 'm^3/mol');
/** Formats molar density (mole per cubic meter). */
export const humanizeMolarDensity = createHumanizeHelperWithPostfix(SI, 'mol/m^3');
/** Formats molar concentration (alias of {@link humanizeConcentration}). */
export const humanizeMolarConcentration = createHumanizeHelperWithPostfix(SI, 'mol/m^3');
/** Formats magnetic flux (weber). */
export const humanizeMagneticFlux = createHumanizeHelperWithPostfix(SI, 'Wb');
/** Formats magnetic flux density (tesla). */
export const humanizeMagneticFluxDensity = createHumanizeHelperWithPostfix(SI, 'T');
/** Formats illuminance (lux). */
export const humanizeIlluminance = createHumanizeHelperWithPostfix(SI, 'lx');
/** Formats luminous flux (lumen). */
export const humanizeLuminousFlux = createHumanizeHelperWithPostfix(SI, 'lm');
/** Formats radioactivity (becquerel). */
export const humanizeRadioactivity = createHumanizeHelperWithPostfix(SI, 'Bq');
/** Formats equivalent dose (sievert). */
export const humanizeRadiationDoseEquivalent = createHumanizeHelperWithPostfix(SI, 'Sv');
/** Formats absorbed dose (gray). */
export const humanizeRadiationDoseAbsorbed = createHumanizeHelperWithPostfix(SI, 'Gy');
/** Formats catalytic activity (katal). */
export const humanizeCatalyticActivity = createHumanizeHelperWithPostfix(SI, 'kat');
