import { type HumanizeUnitOptions, humanizeUnit } from './humanizeUnit.js';
import {
  Acceleration,
  Angle,
  Area,
  Bytes,
  BytesBinary,
  BytesDecimal,
  Capacitance,
  CatalyticActivity,
  Charge,
  Concentration,
  Count,
  Current,
  Density,
  Distance,
  Energy,
  Force,
  Frequency,
  Illuminance,
  Inductance,
  Length,
  LiquidVolume,
  LuminousFlux,
  MagneticFlux,
  MagneticFluxDensity,
  Mass,
  MassFlowRate,
  MolarConcentration,
  MolarDensity,
  MolarMass,
  MolarVolume,
  Momentum,
  Power,
  Pressure,
  RadiationDoseAbsorbed,
  RadiationDoseEquivalent,
  Radioactivity,
  Resistance,
  Storage,
  StorageBinary,
  Temperature,
  TemperatureKelvin,
  Time,
  Torque,
  type UnitArray,
  Velocity,
  Voltage,
  Volume,
  VolumeFlowRate,
} from './units.js';

/**
 * Configuration passed to helper shortcuts. Equivalent to
 * {@link HumanizeUnitOptions} without the `units` table.
 */
export type HumanizeHelperOptions = Omit<HumanizeUnitOptions, 'units'>;

/**
 * Signature shared by all helper functions generated by this module.
 */
export type HumanizeHelper = (value: number | null | undefined, options?: HumanizeHelperOptions) => string;

/**
 * Factory that binds a unit table to `humanizeUnit`.
 *
 * @param units Unit definitions applied by the generated helper.
 * @returns Specialized helper function.
 */
const createHumanizeHelper =
  (units: UnitArray): HumanizeHelper =>
  (value, options) =>
    humanizeUnit(value, { ...options, units });

/** Formats counts using SI prefixes (k, M, G…). */
export const humanizeCount = createHumanizeHelper(Count);
/** Formats decimal bytes (kB, MB, GB…). */
export const humanizeBytes = createHumanizeHelper(Bytes);
/** Alias of {@link humanizeBytes}. */
export const humanizeBytesDecimal = createHumanizeHelper(BytesDecimal);
/** Formats binary bytes (KiB, MiB, GiB…). */
export const humanizeBytesBinary = createHumanizeHelper(BytesBinary);
/** Formats decimal storage capacities. */
export const humanizeStorage = createHumanizeHelper(Storage);
/** Formats binary storage capacities. */
export const humanizeStorageBinary = createHumanizeHelper(StorageBinary);
/** Formats durations from milliseconds to years. */
export const humanizeTime = createHumanizeHelper(Time);
/** Formats distances using SI meters. */
export const humanizeDistance = createHumanizeHelper(Distance);
/** Formats masses using SI grams. */
export const humanizeMass = createHumanizeHelper(Mass);
/** Formats accelerations using meters per second squared. */
export const humanizeAcceleration = createHumanizeHelper(Acceleration);
/** Formats electric charge (coulomb). */
export const humanizeCharge = createHumanizeHelper(Charge);
/** Formats momentum (newton second). */
export const humanizeMomentum = createHumanizeHelper(Momentum);
/** Formats power (watt). */
export const humanizePower = createHumanizeHelper(Power);
/** Formats velocity (meter per second). */
export const humanizeVelocity = createHumanizeHelper(Velocity);
/** Formats volume (cubic meter). */
export const humanizeVolume = createHumanizeHelper(Volume);
/** Formats liquid volume (liter). */
export const humanizeLiquidVolume = createHumanizeHelper(LiquidVolume);
/** Formats temperature in Celsius. */
export const humanizeTemperature = createHumanizeHelper(Temperature);
/** Formats temperature in Kelvin. */
export const humanizeTemperatureKelvin = createHumanizeHelper(TemperatureKelvin);
/** Formats pressure (pascal). */
export const humanizePressure = createHumanizeHelper(Pressure);
/** Formats force (newton). */
export const humanizeForce = createHumanizeHelper(Force);
/** Formats torque (newton meter). */
export const humanizeTorque = createHumanizeHelper(Torque);
/** Formats energy (joule). */
export const humanizeEnergy = createHumanizeHelper(Energy);
/** Formats voltage (volt). */
export const humanizeVoltage = createHumanizeHelper(Voltage);
/** Formats current (ampere). */
export const humanizeCurrent = createHumanizeHelper(Current);
/** Formats resistance (ohm). */
export const humanizeResistance = createHumanizeHelper(Resistance);
/** Formats capacitance (farad). */
export const humanizeCapacitance = createHumanizeHelper(Capacitance);
/** Formats inductance (henry). */
export const humanizeInductance = createHumanizeHelper(Inductance);
/** Formats frequency (hertz). */
export const humanizeFrequency = createHumanizeHelper(Frequency);
/** Formats angle (degree). */
export const humanizeAngle = createHumanizeHelper(Angle);
/** Formats length (meter). */
export const humanizeLength = createHumanizeHelper(Length);
/** Formats area (square meter). */
export const humanizeArea = createHumanizeHelper(Area);
/** Formats volumetric flow rates (cubic meter per second). */
export const humanizeVolumeFlowRate = createHumanizeHelper(VolumeFlowRate);
/** Formats mass flow rates (kilogram per second). */
export const humanizeMassFlowRate = createHumanizeHelper(MassFlowRate);
/** Formats density (kilogram per cubic meter). */
export const humanizeDensity = createHumanizeHelper(Density);
/** Formats concentration (mole per cubic meter). */
export const humanizeConcentration = createHumanizeHelper(Concentration);
/** Formats molar mass (gram per mole). */
export const humanizeMolarMass = createHumanizeHelper(MolarMass);
/** Formats molar volume (cubic meter per mole). */
export const humanizeMolarVolume = createHumanizeHelper(MolarVolume);
/** Formats molar density (mole per cubic meter). */
export const humanizeMolarDensity = createHumanizeHelper(MolarDensity);
/** Formats molar concentration (alias of {@link humanizeConcentration}). */
export const humanizeMolarConcentration = createHumanizeHelper(MolarConcentration);
/** Formats magnetic flux (weber). */
export const humanizeMagneticFlux = createHumanizeHelper(MagneticFlux);
/** Formats magnetic flux density (tesla). */
export const humanizeMagneticFluxDensity = createHumanizeHelper(MagneticFluxDensity);
/** Formats illuminance (lux). */
export const humanizeIlluminance = createHumanizeHelper(Illuminance);
/** Formats luminous flux (lumen). */
export const humanizeLuminousFlux = createHumanizeHelper(LuminousFlux);
/** Formats radioactivity (becquerel). */
export const humanizeRadioactivity = createHumanizeHelper(Radioactivity);
/** Formats equivalent dose (sievert). */
export const humanizeRadiationDoseEquivalent = createHumanizeHelper(RadiationDoseEquivalent);
/** Formats absorbed dose (gray). */
export const humanizeRadiationDoseAbsorbed = createHumanizeHelper(RadiationDoseAbsorbed);
/** Formats catalytic activity (katal). */
export const humanizeCatalyticActivity = createHumanizeHelper(CatalyticActivity);
